//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckoutClient.CheckoutServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckoutServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTotals", ReplyAction="http://tempuri.org/IService/CalculateTotalsResponse")]
        decimal CalculateTotals(System.Collections.Generic.Dictionary<string, int> items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateTotals", ReplyAction="http://tempuri.org/IService/CalculateTotalsResponse")]
        System.Threading.Tasks.Task<decimal> CalculateTotalsAsync(System.Collections.Generic.Dictionary<string, int> items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CheckoutClient.CheckoutServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CheckoutClient.CheckoutServiceReference.IService>, CheckoutClient.CheckoutServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CalculateTotals(System.Collections.Generic.Dictionary<string, int> items) {
            return base.Channel.CalculateTotals(items);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateTotalsAsync(System.Collections.Generic.Dictionary<string, int> items) {
            return base.Channel.CalculateTotalsAsync(items);
        }
    }
}
